packages:
  - .

overrides:
  tailwindcss>nanoid: 3.3.7
  path-to-regexp@0.1.12: 0.1.13

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - "@esbuild/win32-x64"
  - esbuild
  - core-js
