CREATE TABLE `donation_intents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`donationRef` varchar(40) NOT NULL,
	`fullName` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(32) NOT NULL,
	`dob` varchar(10) NOT NULL,
	`panEncrypted` text NOT NULL,
	`panLastFour` varchar(4) NOT NULL,
	`country` varchar(64) NOT NULL DEFAULT 'India',
	`state` varchar(128) NOT NULL,
	`city` varchar(128) NOT NULL,
	`address` text NOT NULL,
	`pincode` varchar(12) NOT NULL,
	`amount` int NOT NULL,
	`status` enum('details_submitted','checkout_created','verified','captured','failed','closed') NOT NULL DEFAULT 'details_submitted',
	`paymentReceipt` varchar(40),
	`notificationStatus` enum('pending','sent','failed') NOT NULL DEFAULT 'pending',
	`notificationSentAt` timestamp,
	`notificationError` varchar(500),
	`consentAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `donation_intents_id` PRIMARY KEY(`id`),
	CONSTRAINT `donation_intents_donationRef_unique` UNIQUE(`donationRef`)
);
--> statement-breakpoint
CREATE TABLE `gallery_media` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mediaRef` varchar(40) NOT NULL,
	`title` varchar(180) NOT NULL,
	`description` text NOT NULL,
	`altText` varchar(500) NOT NULL,
	`quarter` varchar(80) NOT NULL,
	`storageKey` varchar(512) NOT NULL,
	`imageUrl` varchar(1024) NOT NULL,
	`originalName` varchar(255) NOT NULL,
	`mimeType` varchar(100) NOT NULL,
	`fileSize` int NOT NULL,
	`source` enum('manual_upload','google_drive','official_archive') NOT NULL DEFAULT 'manual_upload',
	`sourceFileId` varchar(255),
	`status` enum('draft','published','archived') NOT NULL DEFAULT 'draft',
	`uploadedByOpenId` varchar(64) NOT NULL,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `gallery_media_id` PRIMARY KEY(`id`),
	CONSTRAINT `gallery_media_mediaRef_unique` UNIQUE(`mediaRef`)
);
