import nodemailer from "nodemailer";

type DonationNotificationInput = { donationRef: string; fullName: string; email: string; phone: string; amount: number; state: string; city: string };
type Dependencies = { deliver: (mail: { to: string; subject: string; text: string; html: string }) => Promise<{ messageId?: string }> };

function escapeHtml(value: string) { return value.replace(/[&<'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); }
function smtpConfig() { const host = process.env.SMTP_HOST; const port = Number(process.env.SMTP_PORT); const user = process.env.SMTP_USER; const pass = process.env.SMTP_APP_PASSWORD; if (!host || !port || !user || !pass) throw new Error("Foundation notification sender is not configured."); return { host, port, user, pass }; }
async function deliverWithFoundationGmail(mail: { to: string; subject: string; text: string; html: string }) { const smtp = smtpConfig(); const transport = nodemailer.createTransport({ host: smtp.host, port: smtp.port, secure: smtp.port === 465, requireTLS: smtp.port !== 465, auth: { user: smtp.user, pass: smtp.pass } }); return transport.sendMail({ from: { name: "AASW Foundation", address: smtp.user }, replyTo: smtp.user, ...mail }); }

export function createDonationNotification(input: DonationNotificationInput) {
  const formattedAmount = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(input.amount);
  const text = `New donation details have been received.\n\nDonation reference: ${input.donationRef}\nDonor: ${input.fullName}\nEmail: ${input.email}\nPhone: ${input.phone}\nAmount selected: ${formattedAmount}\nLocation: ${input.city}, ${input.state}\n\nPAN, date of birth and address are not included in this email. Review sensitive records only through the protected Foundation workspace.`;
  const safe = { donationRef: escapeHtml(input.donationRef), fullName: escapeHtml(input.fullName), email: escapeHtml(input.email), phone: escapeHtml(input.phone), amount: escapeHtml(formattedAmount), location: escapeHtml(`${input.city}, ${input.state}`) };
  return { subject: `New donation details · ${input.donationRef}`, text, html: `<!doctype html><html lang="en"><body style="margin:0;background:#fffdf7;color:#291d1d;font-family:Arial,sans-serif"><main style="max-width:620px;margin:0 auto;padding:30px 20px"><section style="border-top:6px solid #d4820a;background:#fffaf0;padding:30px"><p style="margin:0 0 14px;color:#d4820a;font-size:12px;font-weight:700;letter-spacing:1.4px;text-transform:uppercase">AASW Foundation · Donation detail alert</p><h1 style="margin:0;color:#291d1d;font-family:Georgia,serif;font-size:30px;font-weight:400">A new donation path has started.</h1><table role="presentation" style="width:100%;margin-top:24px;border-collapse:collapse"><tr><td style="padding:10px 0;border-top:1px solid #e5ddd4;color:#796966">Reference</td><td style="padding:10px 0;border-top:1px solid #e5ddd4;text-align:right;font-weight:700">${safe.donationRef}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #e5ddd4;color:#796966">Donor</td><td style="padding:10px 0;border-top:1px solid #e5ddd4;text-align:right">${safe.fullName}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #e5ddd4;color:#796966">Contact</td><td style="padding:10px 0;border-top:1px solid #e5ddd4;text-align:right">${safe.email}<br/>${safe.phone}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #e5ddd4;color:#796966">Amount selected</td><td style="padding:10px 0;border-top:1px solid #e5ddd4;text-align:right">${safe.amount}</td></tr><tr><td style="padding:10px 0;border-top:1px solid #e5ddd4;color:#796966">Location</td><td style="padding:10px 0;border-top:1px solid #e5ddd4;text-align:right">${safe.location}</td></tr></table><p style="margin:22px 0 0;color:#796966;font-size:12px;line-height:1.6">For privacy, PAN, date of birth and address are not included in this email. Review sensitive information only in the protected Foundation workspace.</p></section></main></body></html>` };
}

export async function dispatchDonationNotification(input: DonationNotificationInput, dependencies: Dependencies = { deliver: deliverWithFoundationGmail }) { try { const smtp = smtpConfig(); await dependencies.deliver({ to: smtp.user, ...createDonationNotification(input) }); return "sent" as const; } catch (error) { return { status: "failed" as const, error: error instanceof Error ? error.message : "Unknown notification error." }; } }
