import { Check, FileText, ShieldCheck, Users } from "lucide-react";
import { AASW_CONTACT } from "@shared/organisationContact";

type PanelKind = "team" | "governance" | "reports" | "impact" | "membership" | "donate" | "privacy" | "refund";

const councilMembers = ["Abhilash Sharma", "Anjali Juyal", "Ch Parameshwari", "Jainendra Singh", "Kirti Mundra", "Lalit Kumar Dogra", "Mamta Sarda", "Maskura Khatun", "R. Suresh Kumar", "Rajesh", "Renu Singh", "Saguna Shrimali", "Sanjay Bharti", "Soniya Jain", "Subhadra Sahu", "Suman Kori", "Suresh S. Kattimane"];

const goals = ["Encourage Indian states to actively support foundation programs and services.", "Increase presence in rural and urban areas for broad reach and involvement.", "Give special attention to state-specific initiatives for creative social solutions.", "Encourage awareness, self-sufficiency and confidence in digital technology.", "Document and disseminate success stories as inspiration for women in leadership."];

const methodology = ["Market understanding", "Identify local challenges and potential changemakers within community structures.", "Offer tailored digital training and mentorship specialised for women entrepreneurs.", "Follow business development and environmental responsibility in every project.", "Build collaboration on a community and advisory leadership basis for long-term trust.", "Scale successful initiatives through data, feedback and promotion at the state level."];

export function LiveHomeGoalsAndMethodology() {
  return <><section className="section section-sand live-goals-section"><div className="container live-content-heading"><p className="eyebrow"><span className="eyebrow-dot" />Our mission</p><h2>Strategic goals<br /><em>for wider reach.</em></h2></div><div className="container live-goal-grid">{goals.map((goal, index) => <article key={goal}><span>{String(index + 1).padStart(2, "0")}</span><p>{goal}</p></article>)}</div></section><section className="section section-paper live-method-section"><div className="container live-method-layout"><div><p className="eyebrow"><span className="eyebrow-dot" />Our methodology</p><h2>How we work<br /><em>on the ground.</em></h2><p>A sustainable, scalable approach that combines local knowledge with wider standards — built for real outcomes, not one-time efforts.</p></div><ol>{methodology.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><p>{item}</p></li>)}</ol></div></section></>;
}

export function LiveContentAppendix({ kind }: { kind: PanelKind }) {
  if (kind === "team") return <section className="inner-section inner-section-sand live-appendix"><div className="container"><div className="live-appendix-heading"><span className="section-kicker">State Council</span><h2>More people<br /><em>holding the work.</em></h2><p>The live AASW team page identifies these State Council members.</p></div><div className="live-name-grid">{councilMembers.map((name, index) => <div key={name}><span>{String(index + 1).padStart(2, "0")}</span><strong>{name}</strong><small>State Council member</small></div>)}</div></div></section>;
  if (kind === "governance") return <section className="inner-section inner-section-sand live-appendix"><div className="container"><div className="live-appendix-heading"><span className="section-kicker">Policy commitment</span><h2>Safeguards that<br /><em>hold the work steady.</em></h2><p>The Central Advisory Council's functions and the operating safeguards below work together to keep the foundation accountable to the communities it serves.</p></div><div className="live-policy-grid live-policy-grid-secondary">{["Transparency", "Financial auditing", "Anti-corruption", "Conflict of interest", "Whistleblower", "Data privacy"].map((item, index) => <div key={item}><ShieldCheck size={17} /><strong>{item}</strong><p>{index === 0 ? "Public access to deployment and resource-allocation frameworks." : index === 1 ? "Quarterly internal audits and annual external professional assessments." : "A stated operational safeguard on the live governance page."}</p></div>)}</div></div></section>;
  if (kind === "reports") return <section className="inner-section inner-section-sand live-appendix"><div className="container live-report-notice"><FileText size={28} /><div><span className="section-kicker">Latest report notice</span><h2>Fiscal-year documents are being updated.</h2><p>The live AASW reports page states that financial distributions and tax documents are currently being updated for the latest fiscal year. Use the request route below for the latest available record.</p></div></div></section>;
  if (kind === "impact") return <section className="inner-section inner-section-sand live-appendix"><div className="container"><div className="live-appendix-heading"><span className="section-kicker">Public impact snapshot</span><h2>Progress with<br /><em>partnerships in view.</em></h2><p>The live impact page also records active collaboration with schools, colleges and community organisations.</p></div><div className="live-impact-grid">{[["800+", "Women trained in digital skills, entrepreneurship and eco-practices"], ["300+", "Small businesses launched or scaled"], ["30+", "Eco-friendly projects run by women entrepreneurs"], ["5+", "Districts operating with expansion in the pipeline"]].map(([value, label]) => <div key={value}><strong>{value}</strong><p>{label}</p></div>)}</div></div></section>;
  if (kind === "membership") return <section className="inner-section inner-section-paper live-appendix"><div className="container"><div className="live-appendix-heading"><span className="section-kicker">Membership details</span><h2>What members<br /><em>can access.</em></h2></div><div className="live-policy-grid">{["Digital certificate and online community access", "Monthly impact updates and reports", "Quarterly workshops on non-profit management and advocacy", "Early access to annual summits and charity events", "Tax benefits stated under Section 80G", "Regional chapter and national forum eligibility"].map((item) => <div key={item}><Check size={17} /><strong>{item}</strong></div>)}</div></div></section>;
  if (kind === "donate") return <section className="inner-section inner-section-sand live-appendix"><div className="container"><div className="live-appendix-heading"><span className="section-kicker">Contribution choices</span><h2>Direct support for<br /><em>practical pathways.</em></h2><p>The live donation page identifies the following causes and answers common supporter questions. This redesign remains in no-charge demo mode until live credentials are supplied.</p></div><div className="live-policy-grid">{["General donation — deployed where needed most", "Women’s digital literacy and e-commerce skills", "Green and eco-friendly micro-enterprises", "Grassroots leadership and community workshops"].map((item) => <div key={item}><HandIcon /><strong>{item}</strong></div>)}</div><div className="live-faq"><details><summary>Is the donation tax deductible?</summary><p>The live site states that donations qualify for 50% tax exemption under Section 80G when the required PAN information is provided for a receipt.</p></details><details><summary>How is the contribution used?</summary><p>The live site describes funding for digital education workshops, business starter kits and local community outreach, alongside administration and compliance costs.</p></details></div></div></section>;
  if (kind === "privacy") return <section className="inner-section inner-section-sand live-appendix"><div className="container"><div className="live-policy-grid">{[["Information we collect", "Name, email, phone number and mailing address may be collected for donations or memberships. Payment details are processed by gateway partners and are not stored on AASW servers."], ["How information is used", "The live policy lists donation processing, 80G receipts, periodic updates, impact reports and website improvement."], ["Data security", "The policy states that personally identifiable information is not sold, traded or transferred without explicit consent."], ["Contact", `Questions can be directed to ${AASW_CONTACT.email} or ${AASW_CONTACT.primaryPhoneDisplay}.`]].map(([title, copy]) => <div key={title}><strong>{title}</strong><p>{copy}</p></div>)}</div></div></section>;
  return <section className="inner-section inner-section-sand live-appendix"><div className="container"><div className="live-report-notice"><ShieldCheck size={28} /><div><span className="section-kicker">Membership fee policy</span><h2>No refund after an online membership payment.</h2><p>The live refund policy asks supporters to review membership tier details, benefits and pricing before payment. It also states that transactions are processed through secure gateways and financial data is not stored on AASW servers.</p></div></div></div></section>;
}

function HandIcon() { return <Users size={17} />; }
